---
version: 2
jobs:
  build:
    docker:
      - image: node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v1-yarn-{{ .Branch }}
            - v1-yarn-master
      - run: yarn
      - run: {command: "npx jest --coverage", when: always}
      - run: {command: "npx nyc mocha", when: always}
      - run: {command: "npx eslint .", when: always}
      - run: {command: "npx flow check", when: always}
      - run: |
          mv coverage/coverage-final.json coverage/jest-coverage.json
          npx nyc report --reporter=json
          mv coverage/coverage-final.json coverage/mocha-coverage.json
          npx istanbul-combine -r json coverage/*-coverage.json
          bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli-engine-config/node_modules
            - /usr/local/share/.cache/yarn
